---
stages:
  - clean
  - build

variables:
  buildDir: build_01
  cmakeVersion: "3.24.2"
  ninjaVersion: "1.11.1"
  #CI_DEBUG_TRACE: "true"

clean_gitr-u20:
  stage: clean
  tags:
    - gitr-u20
  script:
    - echo cleaning build artifacts from ${CI_PROJECT_DIR}
    - rm -fr ${CI_PROJECT_DIR}/${buildDir}
  allow_failure: true
  when: manual

clean_raptor:
  stage: clean
  tags:
    - raptor
  script:
    - echo cleaning build artifacts from ${CI_PROJECT_DIR}
    - rm -fr ${CI_PROJECT_DIR}/${buildDir}
  allow_failure: true
  when: manual

build_u20:
  stage: build
  tags:
    - cmake
    - ninja
    - ubuntu_20_04
  variables:
    PATH: "/opt/cmake/${cmakeVersion}/bin:\
      /opt/ninja/${ninjaVersion}/bin:\
      /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
    CMAKE_OPTIONS: >-
      -DCMAKE_BUILD_TYPE=RelWithDbgInfo
      -DBUILD_SHARED_LIBS=ON
      -DCMAKE_INSTALL_PREFIX=install
      -DUWEBSOCKETS_BUILD_EXAMPLES=ON
  script:
    - uname -a
    - cmake --version
    - ninja --version
    - "cmake -S . -B ${buildDir} -GNinja ${CMAKE_OPTIONS}"
    - "cmake --build ${buildDir}"
    - "cmake --build ${buildDir} --target install"
  allow_failure: false
