#ifndef SIMPLE_TURN_FAN_ON_PLAN_META_H
#define SIMPLE_TURN_FAN_ON_PLAN_META_H

/******************************************************************************
 * This file has been automatically generated by jack-make
 ******************************************************************************/

/// JACK
#include <jack/plan.h>

/// Third Party
#include <string_view>

namespace aos::jack
{
class BeliefContext;
}


/******************************************************************************
 * \class  TurnFanOnPlanMeta
 * \author jackmake
 * \source simple.jack
 ******************************************************************************/
class TurnFanOnPlanMeta : public aos::jack::Plan
{
public:
    /**************************************************************************
     * Constructor/Destructors
     **************************************************************************/
    TurnFanOnPlanMeta();
    TurnFanOnPlanMeta(std::string_view name);
    TurnFanOnPlanMeta(const TurnFanOnPlanMeta *other);
    virtual ~TurnFanOnPlanMeta() = default;

    /**************************************************************************
     * Functions
     **************************************************************************/
    aos::jack::Plan* clone(JACK_CALL_SITE_ARGS_NO_TAIL_COMMA) const override;

    /// @return True for the plan to be selected and executed, false otherwise.
    virtual bool pre(const aos::jack::BeliefContext& context) = 0;

    /**************************************************************************
     * Static Fields
     **************************************************************************/
    /// The name of the C++ class
    static constexpr inline std::string_view CLASS_NAME = "TurnFanOnPlan";

    /// The name of this object in the JACK model
    static constexpr inline std::string_view MODEL_NAME = "simple.Turn Fan On Plan";
};

#endif /// SIMPLE_TURN_FAN_ON_PLAN_META_H