#ifndef SIMPLE_THERMOSTAT_AGENT_META_H
#define SIMPLE_THERMOSTAT_AGENT_META_H

/******************************************************************************
 * This file has been automatically generated by jack-make
 ******************************************************************************/

/// JACK
#include <jack/agent.h>
#include <jack/handles.h> /// AgentHandle
#include <jack/promise.h>
#include <jack/engine/uuid.h>
#include <jack/events/event.h>

/// Third Party
#include <string_view>

namespace aos::jack
{
class Engine;
}



class TemperatureReading;
class ThermostatAgent;

/******************************************************************************
 * \class  ThermostatAgentMeta
 * \author jackmake
 * \source simple.jack
 ******************************************************************************/
class ThermostatAgentMeta : public aos::jack::Agent
{
public:
    /**************************************************************************
     * Constructor/Destructors
     **************************************************************************/
    ThermostatAgentMeta(aos::jack::Engine& bdi, std::string_view name);
    ThermostatAgentMeta(const ThermostatAgentMeta* other, std::string_view name);
    virtual ~ThermostatAgentMeta() {}

    ThermostatAgentMeta(const ThermostatAgentMeta& other) = delete;
    ThermostatAgentMeta& operator=(const ThermostatAgentMeta& other) = delete;

    /**************************************************************************
     * Functions
     **************************************************************************/
    aos::jack::Agent* clone(std::string_view name) const override;

    /// \note Goals
    aos::jack::GoalPursue pursueMaintainComfort(aos::jack::GoalPersistent persistent, const aos::jack::UniqueId& id = aos::jack::UniqueId::random());

protected:
    /// Link the action handler to this agent's derived action handler.
    void setupHandlers();

public:
    /**************************************************************************
     * Static Functions
     **************************************************************************/
    /// Create an instance of the agent and return the agent handle
    static aos::jack::AgentHandle create(aos::jack::Engine& bdi, std::string_view name, const aos::jack::UniqueId& uuid = aos::jack::UniqueId::random());

    /// Create an instance of the agent and return a pointer to the agent
    static ThermostatAgent* createInstance(aos::jack::Engine& bdi, std::string_view name, const aos::jack::UniqueId& uuid = aos::jack::UniqueId::random());

    /**************************************************************************
     * Static Fields
     **************************************************************************/
    /// The name of the C++ class
    static constexpr inline std::string_view CLASS_NAME = "ThermostatAgent";

    /// The name of this object in the JACK model
    static constexpr inline std::string_view MODEL_NAME = "simple.Thermostat Agent Template";
};

#endif /// SIMPLE_THERMOSTAT_AGENT_META_H