#ifndef SIMPLE_SERVICE_COMPONENTS_H
#define SIMPLE_SERVICE_COMPONENTS_H

/******************************************************************************
 * This file has been automatically generated by jack-make
 ******************************************************************************/

#if defined(JACK_WITH_SIM)
/******************************************************************************
 * The JACK services as component for integration with the simulator
 ******************************************************************************/
#include <simple/impl/services/fanserviceimpl.h>
#include <sim/components/service.h>


/******************************************************************************
 * The JACK services as component for integration with the simulator
 ******************************************************************************/
using FanServiceComponent = aos::sim::ServiceComponent<FanService>;

#endif /// defined(JACK_WITH_SIM)
#endif /// SIMPLE_SERVICE_COMPONENTS_H