cmake_minimum_required(VERSION 3.22.1)

# This file is automatically generated by jack-make and generates CMake
# target and variables for the JACK project that includes the file.
#
# Project: simple
#
# Options
# - JACK_MAKE_GENERATED_HEADERS_SIMPLE
#   CMake variable containing the list of header files that were generated.
#
# - JACK_MAKE_GENERATED_SOURCES_SIMPLE
#   CMake variable containing the list of source files that were generated.
#
# - JACK_MAKE_GENERATED_INCLUDE_DIRS_SIMPLE
#   CMake variable containing the include directories for the project

# Options
# Variables
set(JACK_MAKE_GENERATED_HEADERS_SIMPLE
    # Project
    ${CMAKE_CURRENT_LIST_DIR}/../meta/simpleproject.h

    # Beliefsets
    ${CMAKE_CURRENT_LIST_DIR}/../meta/messages/temperaturereadingmeta.h
    ${CMAKE_CURRENT_LIST_DIR}/../meta/messages/fancontrolmeta.h

    # Agents
    ${CMAKE_CURRENT_LIST_DIR}/../impl/agents/thermostatagentimpl.h
    ${CMAKE_CURRENT_LIST_DIR}/../meta/agents/thermostatagentmeta.h

    # Teams

    # Goals
    ${CMAKE_CURRENT_LIST_DIR}/../impl/goals/maintaincomfortimpl.h
    ${CMAKE_CURRENT_LIST_DIR}/../meta/goals/maintaincomfortmeta.h

    # Plans
    ${CMAKE_CURRENT_LIST_DIR}/../meta/plans/turnfanonplanmeta.h
    ${CMAKE_CURRENT_LIST_DIR}/../impl/plans/turnfanonplanimpl.h
    ${CMAKE_CURRENT_LIST_DIR}/../meta/plans/turnfanoffplanmeta.h
    ${CMAKE_CURRENT_LIST_DIR}/../impl/plans/turnfanoffplanimpl.h

    # Services
    ${CMAKE_CURRENT_LIST_DIR}/../impl/services/fanserviceimpl.h
    ${CMAKE_CURRENT_LIST_DIR}/../meta/services/fanservicemeta.h

    # Other
    ${CMAKE_CURRENT_LIST_DIR}/../meta/simpleenumsmeta.h
    ${CMAKE_CURRENT_LIST_DIR}/../meta/simpleservicecomponents.h
)

set(JACK_MAKE_GENERATED_SOURCES_SIMPLE
    ${CMAKE_CURRENT_LIST_DIR}/../meta/simpleproject.cpp

    # Beliefsets
    ${CMAKE_CURRENT_LIST_DIR}/../meta/messages/temperaturereadingmeta.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../meta/messages/fancontrolmeta.cpp

    # Agents
    ${CMAKE_CURRENT_LIST_DIR}/../impl/agents/thermostatagentimpl.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../meta/agents/thermostatagentmeta.cpp

    # Teams

    # Goals
    ${CMAKE_CURRENT_LIST_DIR}/../meta/goals/maintaincomfortmeta.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../impl/goals/maintaincomfortimpl.cpp

    # Plans
    ${CMAKE_CURRENT_LIST_DIR}/../meta/plans/turnfanonplanmeta.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../impl/plans/turnfanonplanimpl.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../meta/plans/turnfanoffplanmeta.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../impl/plans/turnfanoffplanimpl.cpp

    # Services
    ${CMAKE_CURRENT_LIST_DIR}/../impl/services/fanserviceimpl.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../meta/services/fanservicemeta.cpp

    # Enums
    ${CMAKE_CURRENT_LIST_DIR}/../meta/simpleenumsmeta.cpp
)

set(JACK_MAKE_GENERATED_INCLUDE_DIRS_SIMPLE ${CMAKE_CURRENT_LIST_DIR}/../..)