#ifndef SIMPLE_EVENTS_H
#define SIMPLE_EVENTS_H

/******************************************************************************
 * This file has been automatically generated by jack-make
 ******************************************************************************/

/// simple

/// Sim
#include <sim/simevent.h>
#include <sim/sim.h>

/// JACK
#include <jack/handles.h>

/// Third Party
#include <nlohmann/json.hpp>
#include <string>
#include <string_view>



#endif /// SIMPLE_EVENTS_H