#ifndef SIMPLE_MAINTAIN_COMFORT_META_H
#define SIMPLE_MAINTAIN_COMFORT_META_H

/******************************************************************************
 * This file has been automatically generated by jack-make
 ******************************************************************************/

/// JACK
#include <jack/goal.h>

/// Third Party
#include <string_view>

namespace aos::jack
{
class BeliefContext;
}




/******************************************************************************
 * \class  MaintainComfortMeta
 * \author jackmake
 * \source simple.jack
 ******************************************************************************/
class MaintainComfortMeta : public aos::jack::Goal
{
public:
    /**************************************************************************
     * Constructor/Destructors
     **************************************************************************/
    MaintainComfortMeta();
    MaintainComfortMeta(std::string_view name);
    MaintainComfortMeta(const MaintainComfortMeta *other);

    /**************************************************************************
     * Functions
     **************************************************************************/
    aos::jack::Goal* clone(JACK_CALL_SITE_ARGS_NO_TAIL_COMMA) const override;

    /**************************************************************************
     * Static Functions
     **************************************************************************/

    /**************************************************************************
     * Static Fields
     **************************************************************************/
    /// The name of the class
    static constexpr inline std::string_view CLASS_NAME = "MaintainComfort";

    /// The name of this object in the JACK model
    static constexpr inline std::string_view MODEL_NAME = "simple.Maintain Comfort";
};

#endif /// SIMPLE_MAINTAIN_COMFORT_META_H