#ifndef GOL_ENUMS_META_H
#define GOL_ENUMS_META_H

/******************************************************************************
 * This file has been automatically generated by jack-make
 ******************************************************************************/

/// Third Party
#include <nlohmann/json.hpp>
#include <string_view>






#endif /// GOL_ENUMS_META_H