#ifndef GOL_SERVICE_COMPONENTS_H
#define GOL_SERVICE_COMPONENTS_H

/******************************************************************************
 * This file has been automatically generated by jack-make
 ******************************************************************************/

#if defined(JACK_WITH_SIM)
/******************************************************************************
 * The JACK services as component for integration with the simulator
 ******************************************************************************/
#include <gol/impl/services/gameoflifeserviceimpl.h>
#include <sim/components/service.h>


/******************************************************************************
 * The JACK services as component for integration with the simulator
 ******************************************************************************/
using GameOfLifeServiceComponent = aos::sim::ServiceComponent<GameOfLifeService>;

#endif /// defined(JACK_WITH_SIM)
#endif /// GOL_SERVICE_COMPONENTS_H