#ifndef GOL_MODEL_LIFE_META_H
#define GOL_MODEL_LIFE_META_H

/******************************************************************************
 * This file has been automatically generated by jack-make
 ******************************************************************************/

/// JACK
#include <jack/goal.h>

/// Third Party
#include <string_view>

namespace aos::jack
{
class BeliefContext;
}




/******************************************************************************
 * \class  ModelLifeMeta
 * \author jackmake
 * \source gol.jack
 ******************************************************************************/
class ModelLifeMeta : public aos::jack::Goal
{
public:
    /**************************************************************************
     * Constructor/Destructors
     **************************************************************************/
    ModelLifeMeta();
    ModelLifeMeta(std::string_view name);
    ModelLifeMeta(const ModelLifeMeta *other);

    /**************************************************************************
     * Functions
     **************************************************************************/
    aos::jack::Goal* clone(JACK_CALL_SITE_ARGS_NO_TAIL_COMMA) const override;

    /**************************************************************************
     * Static Functions
     **************************************************************************/

    /**************************************************************************
     * Static Fields
     **************************************************************************/
    /// The name of the class
    static constexpr inline std::string_view CLASS_NAME = "ModelLife";

    /// The name of this object in the JACK model
    static constexpr inline std::string_view MODEL_NAME = "gol.Model Life";
};

#endif /// GOL_MODEL_LIFE_META_H