#ifndef GOL_LIVE_PLAN_META_H
#define GOL_LIVE_PLAN_META_H

/******************************************************************************
 * This file has been automatically generated by jack-make
 ******************************************************************************/

/// JACK
#include <jack/plan.h>

/// Third Party
#include <string_view>

namespace aos::jack
{
class BeliefContext;
}


/******************************************************************************
 * \class  LivePlanMeta
 * \author jackmake
 * \source gol.jack
 ******************************************************************************/
class LivePlanMeta : public aos::jack::Plan
{
public:
    /**************************************************************************
     * Constructor/Destructors
     **************************************************************************/
    LivePlanMeta();
    LivePlanMeta(std::string_view name);
    LivePlanMeta(const LivePlanMeta *other);
    virtual ~LivePlanMeta() = default;

    /**************************************************************************
     * Functions
     **************************************************************************/
    aos::jack::Plan* clone(JACK_CALL_SITE_ARGS_NO_TAIL_COMMA) const override;

    /// @return True for the plan to be selected and executed, false otherwise.
    virtual bool pre(const aos::jack::BeliefContext& context) = 0;

    /**************************************************************************
     * Static Fields
     **************************************************************************/
    /// The name of the C++ class
    static constexpr inline std::string_view CLASS_NAME = "LivePlan";

    /// The name of this object in the JACK model
    static constexpr inline std::string_view MODEL_NAME = "gol.Live Plan";
};

#endif /// GOL_LIVE_PLAN_META_H