set(SHA1_googletest origin/feature/mw/upstream)
set(SHA1_cyclonedds origin/maint/aos/0.10.3)
set(SHA1_cyclonedds_cxx origin/maint/aos/0.10.3)
set(SHA1_flatbuffers origin/feature/mw/jack_install)
set(SHA1_concurrentqueue origin/feature/mw/fix_includes)
set(SHA1_uwebsockets origin/feature/mw/fix_includes)
